<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-NIPG9B05" name="test.scripts.forgotUserName_1005b" tests="1" failures="1" timestamp="7 Sep 2017 21:17:38 GMT" time="48.593" errors="0">
  <testcase name="verify_forgotUserName_1005b" time="48.593" classname="test.scripts.forgotUserName_1005b">
    <failure type="java.lang.AssertionError" message="timeout error: element &#039;btn_OK_alert_UsernameRecovery&#039; not present">
      <![CDATA[java.lang.AssertionError: timeout error: element 'btn_OK_alert_UsernameRecovery' not present
	at org.testng.Assert.fail(Assert.java:94)
	at test.com.functions.BaseClass.WaitForElementPresent(BaseClass.java:173)
	at test.com.functions.business_functions.usernameRecoveryInvalid(business_functions.java:150)
	at test.scripts.forgotUserName_1005b.verify_forgotUserName_1005b(forgotUserName_1005b.java:214)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at net.randomsync.testng.excel.ExcelTestNGRunner.run(ExcelTestNGRunner.java:98)
	at main.Mainscript.main(Mainscript.java:13)
]]>
    </failure>
  </testcase> <!-- verify_forgotUserName_1005b -->
</testsuite> <!-- test.scripts.forgotUserName_1005b -->
